
title: Wallace
author: Wallace
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A description of your site should go here. Keep it short and snappy.
  It will appear in your document head meta (for Google search results)
  and in your feed.xml site description.

# Wallace date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
wallace:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - cv.md

# Build settings
markdown: kramdown
theme: jekyll-theme-wallace
exclude:
  - Gemfile
  - Gemfile.lock
